import type { Metadata } from "next";
import {Inter, Poppins}from "next/font/google";
import "./globals.css";
import { Providers } from "./sessionProvider";

const inter = Inter({
  subsets: ['latin'], 
  weight: ["100","200","300","400","500","600","700","800","900"], 
  variable: '--font-inter', 
});
const poppins = Poppins({
  subsets: ['latin'], 
  weight: ["100","200","300","400","500","600","700","800","900"], 
  variable: '--font-poppins', 
});

export const metadata: Metadata = {
  title: "MindTasker",
  description: "Generated by MindTasker",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${poppins.variable}`}
      >
        <Providers>
         {children}
        </Providers>
      </body>
    </html>
  );
}
